/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SanctuaryRouteImport } from './routes/sanctuary'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SanctuaryToolkitRouteImport } from './routes/sanctuary.toolkit'
import { Route as SanctuaryMirrorRouteImport } from './routes/sanctuary.mirror'
import { Route as SanctuaryInsightsRouteImport } from './routes/sanctuary.insights'
import { Route as SanctuaryCrisisRouteImport } from './routes/sanctuary.crisis'
import { Route as SanctuaryChatRouteImport } from './routes/sanctuary.chat'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SanctuaryRoute = SanctuaryRouteImport.update({
  id: '/sanctuary',
  path: '/sanctuary',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SanctuaryToolkitRoute = SanctuaryToolkitRouteImport.update({
  id: '/toolkit',
  path: '/toolkit',
  getParentRoute: () => SanctuaryRoute,
} as any)
const SanctuaryMirrorRoute = SanctuaryMirrorRouteImport.update({
  id: '/mirror',
  path: '/mirror',
  getParentRoute: () => SanctuaryRoute,
} as any)
const SanctuaryInsightsRoute = SanctuaryInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => SanctuaryRoute,
} as any)
const SanctuaryCrisisRoute = SanctuaryCrisisRouteImport.update({
  id: '/crisis',
  path: '/crisis',
  getParentRoute: () => SanctuaryRoute,
} as any)
const SanctuaryChatRoute = SanctuaryChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => SanctuaryRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sanctuary': typeof SanctuaryRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/sanctuary/chat': typeof SanctuaryChatRoute
  '/sanctuary/crisis': typeof SanctuaryCrisisRoute
  '/sanctuary/insights': typeof SanctuaryInsightsRoute
  '/sanctuary/mirror': typeof SanctuaryMirrorRoute
  '/sanctuary/toolkit': typeof SanctuaryToolkitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sanctuary': typeof SanctuaryRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/sanctuary/chat': typeof SanctuaryChatRoute
  '/sanctuary/crisis': typeof SanctuaryCrisisRoute
  '/sanctuary/insights': typeof SanctuaryInsightsRoute
  '/sanctuary/mirror': typeof SanctuaryMirrorRoute
  '/sanctuary/toolkit': typeof SanctuaryToolkitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sanctuary': typeof SanctuaryRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/sanctuary/chat': typeof SanctuaryChatRoute
  '/sanctuary/crisis': typeof SanctuaryCrisisRoute
  '/sanctuary/insights': typeof SanctuaryInsightsRoute
  '/sanctuary/mirror': typeof SanctuaryMirrorRoute
  '/sanctuary/toolkit': typeof SanctuaryToolkitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sanctuary'
    | '/api/chat'
    | '/sanctuary/chat'
    | '/sanctuary/crisis'
    | '/sanctuary/insights'
    | '/sanctuary/mirror'
    | '/sanctuary/toolkit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sanctuary'
    | '/api/chat'
    | '/sanctuary/chat'
    | '/sanctuary/crisis'
    | '/sanctuary/insights'
    | '/sanctuary/mirror'
    | '/sanctuary/toolkit'
  id:
    | '__root__'
    | '/'
    | '/sanctuary'
    | '/api/chat'
    | '/sanctuary/chat'
    | '/sanctuary/crisis'
    | '/sanctuary/insights'
    | '/sanctuary/mirror'
    | '/sanctuary/toolkit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SanctuaryRoute: typeof SanctuaryRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sanctuary': {
      id: '/sanctuary'
      path: '/sanctuary'
      fullPath: '/sanctuary'
      preLoaderRoute: typeof SanctuaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanctuary/toolkit': {
      id: '/sanctuary/toolkit'
      path: '/toolkit'
      fullPath: '/sanctuary/toolkit'
      preLoaderRoute: typeof SanctuaryToolkitRouteImport
      parentRoute: typeof SanctuaryRoute
    }
    '/sanctuary/mirror': {
      id: '/sanctuary/mirror'
      path: '/mirror'
      fullPath: '/sanctuary/mirror'
      preLoaderRoute: typeof SanctuaryMirrorRouteImport
      parentRoute: typeof SanctuaryRoute
    }
    '/sanctuary/insights': {
      id: '/sanctuary/insights'
      path: '/insights'
      fullPath: '/sanctuary/insights'
      preLoaderRoute: typeof SanctuaryInsightsRouteImport
      parentRoute: typeof SanctuaryRoute
    }
    '/sanctuary/crisis': {
      id: '/sanctuary/crisis'
      path: '/crisis'
      fullPath: '/sanctuary/crisis'
      preLoaderRoute: typeof SanctuaryCrisisRouteImport
      parentRoute: typeof SanctuaryRoute
    }
    '/sanctuary/chat': {
      id: '/sanctuary/chat'
      path: '/chat'
      fullPath: '/sanctuary/chat'
      preLoaderRoute: typeof SanctuaryChatRouteImport
      parentRoute: typeof SanctuaryRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SanctuaryRouteChildren {
  SanctuaryChatRoute: typeof SanctuaryChatRoute
  SanctuaryCrisisRoute: typeof SanctuaryCrisisRoute
  SanctuaryInsightsRoute: typeof SanctuaryInsightsRoute
  SanctuaryMirrorRoute: typeof SanctuaryMirrorRoute
  SanctuaryToolkitRoute: typeof SanctuaryToolkitRoute
}

const SanctuaryRouteChildren: SanctuaryRouteChildren = {
  SanctuaryChatRoute: SanctuaryChatRoute,
  SanctuaryCrisisRoute: SanctuaryCrisisRoute,
  SanctuaryInsightsRoute: SanctuaryInsightsRoute,
  SanctuaryMirrorRoute: SanctuaryMirrorRoute,
  SanctuaryToolkitRoute: SanctuaryToolkitRoute,
}

const SanctuaryRouteWithChildren = SanctuaryRoute._addFileChildren(
  SanctuaryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SanctuaryRoute: SanctuaryRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
